name: Deploy to Vercel
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: 'team_f6mg2AXANLWsOvelJb49WN4l'
          vercel-project-id: 'prj_oQVyaevJtLXNWHRKLvniW8PUzHTt'
          vercel-args: '--prod'
